/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.20
 * Generated at: 2020-04-30 02:58:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"renderer\" content=\"webkit|ie-comp|ie-stand\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"width=device-width,initial-scale=1,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no\" />\r\n");
      out.write("<meta http-equiv=\"Cache-Control\" content=\"no-siteapp\" />\r\n");
      out.write("<link rel=\"Bookmark\" href=\"/favicon.ico\">\r\n");
      out.write("<link rel=\"Shortcut Icon\" href=\"/favicon.ico\" />\r\n");
      out.write("<!--[if lt IE 9]>\r\n");
      out.write("<script type=\"text/javascript\" src=\"lib/html5shiv.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"lib/respond.min.js\"></script>\r\n");
      out.write("<![endif]-->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"static/h-ui/css/H-ui.min.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"static/h-ui.admin/css/H-ui.admin.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"lib/Hui-iconfont/1.0.8/iconfont.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"static/h-ui.admin/skin/default/skin.css\" id=\"skin\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"static/h-ui.admin/css/style.css\" />\r\n");
      out.write("<!--[if IE 6]>\r\n");
      out.write("<script type=\"text/javascript\" src=\"lib/DD_belatedPNG_0.0.8a-min.js\" ></script>\r\n");
      out.write("<script>DD_belatedPNG.fix('*');</script>\r\n");
      out.write("<![endif]-->\r\n");
      out.write("<title>H-ui.admin v3.1</title>\r\n");
      out.write("<meta name=\"keywords\"\r\n");
      out.write("\tcontent=\"H-ui.admin v3.1,H-ui网站后台模版,后台模版下载,后台管理系统模版,HTML后台模版下载\">\r\n");
      out.write("<meta name=\"description\"\r\n");
      out.write("\tcontent=\"H-ui.admin v3.1，是一款由国人开发的轻量级扁平化网站后台模板，完全免费开源的网站后台管理系统模版，适合中小型CMS后台系统。\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<header class=\"navbar-wrapper\">\r\n");
      out.write("\t<div class=\"navbar navbar-fixed-top\">\r\n");
      out.write("\t\t<div class=\"container-fluid cl\">\r\n");
      out.write("\t\t\t<a class=\"logo navbar-logo f-l mr-10 hidden-xs\"\r\n");
      out.write("\t\t\t\thref=\"/aboutHui.shtml\">H-ui.admin</a> <a\r\n");
      out.write("\t\t\t\tclass=\"logo navbar-logo-m f-l mr-10 visible-xs\"\r\n");
      out.write("\t\t\t\thref=\"/aboutHui.shtml\">H-ui</a> <span\r\n");
      out.write("\t\t\t\tclass=\"logo navbar-slogan f-l mr-10 hidden-xs\">v3.1</span> <a\r\n");
      out.write("\t\t\t\taria-hidden=\"false\" class=\"nav-toggle Hui-iconfont visible-xs\"\r\n");
      out.write("\t\t\t\thref=\"javascript:;\">&#xe667;</a>\r\n");
      out.write("\t\t\t<nav class=\"nav navbar-nav\">\r\n");
      out.write("\t\t\t<ul class=\"cl\">\r\n");
      out.write("\t\t\t\t<li class=\"dropDown dropDown_hover\"><a href=\"javascript:;\"\r\n");
      out.write("\t\t\t\t\tclass=\"dropDown_A\"><i class=\"Hui-iconfont\">&#xe600;</i> 新增 <i\r\n");
      out.write("\t\t\t\t\t\tclass=\"Hui-iconfont\">&#xe6d5;</i></a>\r\n");
      out.write("\t\t\t\t\t<ul class=\"dropDown-menu menu radius box-shadow\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"javascript:;\"\r\n");
      out.write("\t\t\t\t\t\t\tonclick=\"article_add('添加资讯','article-add.html')\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"Hui-iconfont\">&#xe616;</i> 资讯</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"javascript:;\"\r\n");
      out.write("\t\t\t\t\t\t\tonclick=\"picture_add('添加资讯','picture-add.html')\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"Hui-iconfont\">&#xe613;</i> 图片</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"javascript:;\"\r\n");
      out.write("\t\t\t\t\t\t\tonclick=\"product_add('添加资讯','product-add.html')\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"Hui-iconfont\">&#xe620;</i> 产品</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"javascript:;\"\r\n");
      out.write("\t\t\t\t\t\t\tonclick=\"member_add('添加用户','member-add.html','','510')\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"Hui-iconfont\">&#xe60d;</i> 用户</a></li>\r\n");
      out.write("\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t</nav>\r\n");
      out.write("\t\t\t<nav id=\"Hui-userbar\" class=\"nav navbar-nav navbar-userbar hidden-xs\">\r\n");
      out.write("\t\t\t<ul class=\"cl\">\r\n");
      out.write("\t\t\t\t<li>超级管理员</li>\r\n");
      out.write("\t\t\t\t<li class=\"dropDown dropDown_hover\"><a href=\"#\"\r\n");
      out.write("\t\t\t\t\tclass=\"dropDown_A\"><i class=\"Hui-iconfont\">&#xe6d5;</i></a>\r\n");
      out.write("\t\t\t\t\t<ul class=\"dropDown-menu menu radius box-shadow\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"javascript:;\" onClick=\"myselfinfo()\">个人信息</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">切换账户</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">退出</a></li>\r\n");
      out.write("\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t<li id=\"Hui-msg\"><a href=\"#\" title=\"消息\"><span\r\n");
      out.write("\t\t\t\t\t\tclass=\"badge badge-danger\">1</span><i class=\"Hui-iconfont\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"font-size: 18px\">&#xe68a;</i></a></li>\r\n");
      out.write("\t\t\t\t<li id=\"Hui-skin\" class=\"dropDown right dropDown_hover\"><a\r\n");
      out.write("\t\t\t\t\thref=\"javascript:;\" class=\"dropDown_A\" title=\"换肤\"><i\r\n");
      out.write("\t\t\t\t\t\tclass=\"Hui-iconfont\" style=\"font-size: 18px\">&#xe62a;</i></a>\r\n");
      out.write("\t\t\t\t\t<ul class=\"dropDown-menu menu radius box-shadow\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"javascript:;\" data-val=\"default\" title=\"默认（黑色）\">默认（黑色）</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"javascript:;\" data-val=\"blue\" title=\"蓝色\">蓝色</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"javascript:;\" data-val=\"green\" title=\"绿色\">绿色</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"javascript:;\" data-val=\"red\" title=\"红色\">红色</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"javascript:;\" data-val=\"yellow\" title=\"黄色\">黄色</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"javascript:;\" data-val=\"orange\" title=\"橙色\">橙色</a></li>\r\n");
      out.write("\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t</nav>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</header>\r\n");
      out.write("\t<aside class=\"Hui-aside\">\r\n");
      out.write("\t<div class=\"menu_dropdown bk_2\">\r\n");
      out.write("\t\t<dl id=\"menu-article\">\r\n");
      out.write("\t\t\t<dt>\r\n");
      out.write("\t\t\t\t<i class=\"Hui-iconfont\">&#xe616;</i> 资讯管理<i\r\n");
      out.write("\t\t\t\t\tclass=\"Hui-iconfont menu_dropdown-arrow\">&#xe6d5;</i>\r\n");
      out.write("\t\t\t</dt>\r\n");
      out.write("\t\t\t<dd>\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li><a data-href=\"UserlistServlet\" data-title=\"用户管理\"\r\n");
      out.write("\t\t\t\t\t\thref=\"javascript:void(0)\">用户管理</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li><a data-href=\"MapServlet\" data-title=\"百度地图\"\r\n");
      out.write("\t\t\t\t\t\thref=\"javascript:void(0)\">百度地图</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</dd>\r\n");
      out.write("\t\t</dl>\r\n");
      out.write("\t\t<dl id=\"menu-picture\">\r\n");
      out.write("\t\t\t<dt>\r\n");
      out.write("\t\t\t\t<i class=\"Hui-iconfont\">&#xe613;</i> 图片管理<i\r\n");
      out.write("\t\t\t\t\tclass=\"Hui-iconfont menu_dropdown-arrow\">&#xe6d5;</i>\r\n");
      out.write("\t\t\t</dt>\r\n");
      out.write("\t\t\t<dd>\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li><a data-href=\"picture-list.html\" data-title=\"图片管理\"\r\n");
      out.write("\t\t\t\t\t\thref=\"javascript:void(0)\">图片管理</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</dd>\r\n");
      out.write("\t\t</dl>\r\n");
      out.write("\t\t<dl id=\"menu-product\">\r\n");
      out.write("\t\t\t<dt>\r\n");
      out.write("\t\t\t\t<i class=\"Hui-iconfont\">&#xe620;</i> 产品管理<i\r\n");
      out.write("\t\t\t\t\tclass=\"Hui-iconfont menu_dropdown-arrow\">&#xe6d5;</i>\r\n");
      out.write("\t\t\t</dt>\r\n");
      out.write("\t\t\t<dd>\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li><a data-href=\"product-brand.html\" data-title=\"品牌管理\"\r\n");
      out.write("\t\t\t\t\t\thref=\"javascript:void(0)\">品牌管理</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a data-href=\"product-category.html\" data-title=\"分类管理\"\r\n");
      out.write("\t\t\t\t\t\thref=\"javascript:void(0)\">分类管理</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a data-href=\"product-list.html\" data-title=\"产品管理\"\r\n");
      out.write("\t\t\t\t\t\thref=\"javascript:void(0)\">产品管理</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</dd>\r\n");
      out.write("\t\t</dl>\r\n");
      out.write("\t\t<dl id=\"menu-comments\">\r\n");
      out.write("\t\t\t<dt>\r\n");
      out.write("\t\t\t\t<i class=\"Hui-iconfont\">&#xe622;</i> 评论管理<i\r\n");
      out.write("\t\t\t\t\tclass=\"Hui-iconfont menu_dropdown-arrow\">&#xe6d5;</i>\r\n");
      out.write("\t\t\t</dt>\r\n");
      out.write("\t\t\t<dd>\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li><a data-href=\"http://h-ui.duoshuo.com/admin/\"\r\n");
      out.write("\t\t\t\t\t\tdata-title=\"评论列表\" href=\"javascript:;\">评论列表</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a data-href=\"feedback-list.html\" data-title=\"意见反馈\"\r\n");
      out.write("\t\t\t\t\t\thref=\"javascript:void(0)\">意见反馈</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</dd>\r\n");
      out.write("\t\t</dl>\r\n");
      out.write("\t\t<dl id=\"menu-member\">\r\n");
      out.write("\t\t\t<dt>\r\n");
      out.write("\t\t\t\t<i class=\"Hui-iconfont\">&#xe60d;</i> 会员管理<i\r\n");
      out.write("\t\t\t\t\tclass=\"Hui-iconfont menu_dropdown-arrow\">&#xe6d5;</i>\r\n");
      out.write("\t\t\t</dt>\r\n");
      out.write("\t\t\t<dd>\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li><a data-href=\"member-list.html\" data-title=\"会员列表\"\r\n");
      out.write("\t\t\t\t\t\thref=\"javascript:;\">会员列表</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a data-href=\"member-del.html\" data-title=\"删除的会员\"\r\n");
      out.write("\t\t\t\t\t\thref=\"javascript:;\">删除的会员</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a data-href=\"member-level.html\" data-title=\"等级管理\"\r\n");
      out.write("\t\t\t\t\t\thref=\"javascript:;\">等级管理</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a data-href=\"member-scoreoperation.html\"\r\n");
      out.write("\t\t\t\t\t\tdata-title=\"积分管理\" href=\"javascript:;\">积分管理</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a data-href=\"member-record-browse.html\" data-title=\"浏览记录\"\r\n");
      out.write("\t\t\t\t\t\thref=\"javascript:void(0)\">浏览记录</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a data-href=\"member-record-download.html\"\r\n");
      out.write("\t\t\t\t\t\tdata-title=\"下载记录\" href=\"javascript:void(0)\">下载记录</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a data-href=\"member-record-share.html\" data-title=\"分享记录\"\r\n");
      out.write("\t\t\t\t\t\thref=\"javascript:void(0)\">分享记录</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</dd>\r\n");
      out.write("\t\t</dl>\r\n");
      out.write("\t\t<dl id=\"menu-admin\">\r\n");
      out.write("\t\t\t<dt>\r\n");
      out.write("\t\t\t\t<i class=\"Hui-iconfont\">&#xe62d;</i> 管理员管理<i\r\n");
      out.write("\t\t\t\t\tclass=\"Hui-iconfont menu_dropdown-arrow\">&#xe6d5;</i>\r\n");
      out.write("\t\t\t</dt>\r\n");
      out.write("\t\t\t<dd>\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li><a data-href=\"admin-role.html\" data-title=\"角色管理\"\r\n");
      out.write("\t\t\t\t\t\thref=\"javascript:void(0)\">角色管理</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a data-href=\"admin-permission.html\" data-title=\"权限管理\"\r\n");
      out.write("\t\t\t\t\t\thref=\"javascript:void(0)\">权限管理</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a data-href=\"admin-list.html\" data-title=\"管理员列表\"\r\n");
      out.write("\t\t\t\t\t\thref=\"javascript:void(0)\">管理员列表</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</dd>\r\n");
      out.write("\t\t</dl>\r\n");
      out.write("\t\t<dl id=\"menu-tongji\">\r\n");
      out.write("\t\t\t<dt>\r\n");
      out.write("\t\t\t\t<i class=\"Hui-iconfont\">&#xe61a;</i> 系统统计<i\r\n");
      out.write("\t\t\t\t\tclass=\"Hui-iconfont menu_dropdown-arrow\">&#xe6d5;</i>\r\n");
      out.write("\t\t\t</dt>\r\n");
      out.write("\t\t\t<dd>\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li><a data-href=\"charts-1.html\" data-title=\"折线图\"\r\n");
      out.write("\t\t\t\t\t\thref=\"javascript:void(0)\">折线图</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a data-href=\"charts-2.html\" data-title=\"时间轴折线图\"\r\n");
      out.write("\t\t\t\t\t\thref=\"javascript:void(0)\">时间轴折线图</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a data-href=\"charts-3.html\" data-title=\"区域图\"\r\n");
      out.write("\t\t\t\t\t\thref=\"javascript:void(0)\">区域图</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a data-href=\"charts-4.html\" data-title=\"柱状图\"\r\n");
      out.write("\t\t\t\t\t\thref=\"javascript:void(0)\">柱状图</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a data-href=\"charts-5.html\" data-title=\"饼状图\"\r\n");
      out.write("\t\t\t\t\t\thref=\"javascript:void(0)\">饼状图</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a data-href=\"charts-6.html\" data-title=\"3D柱状图\"\r\n");
      out.write("\t\t\t\t\t\thref=\"javascript:void(0)\">3D柱状图</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a data-href=\"charts-7.html\" data-title=\"3D饼状图\"\r\n");
      out.write("\t\t\t\t\t\thref=\"javascript:void(0)\">3D饼状图</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</dd>\r\n");
      out.write("\t\t</dl>\r\n");
      out.write("\t\t<dl id=\"menu-system\">\r\n");
      out.write("\t\t\t<dt>\r\n");
      out.write("\t\t\t\t<i class=\"Hui-iconfont\">&#xe62e;</i> 系统管理<i\r\n");
      out.write("\t\t\t\t\tclass=\"Hui-iconfont menu_dropdown-arrow\">&#xe6d5;</i>\r\n");
      out.write("\t\t\t</dt>\r\n");
      out.write("\t\t\t<dd>\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li><a data-href=\"system-base.html\" data-title=\"系统设置\"\r\n");
      out.write("\t\t\t\t\t\thref=\"javascript:void(0)\">系统设置</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a data-href=\"system-category.html\" data-title=\"栏目管理\"\r\n");
      out.write("\t\t\t\t\t\thref=\"javascript:void(0)\">栏目管理</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a data-href=\"system-data.html\" data-title=\"数据字典\"\r\n");
      out.write("\t\t\t\t\t\thref=\"javascript:void(0)\">数据字典</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a data-href=\"system-shielding.html\" data-title=\"屏蔽词\"\r\n");
      out.write("\t\t\t\t\t\thref=\"javascript:void(0)\">屏蔽词</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a data-href=\"system-log.html\" data-title=\"系统日志\"\r\n");
      out.write("\t\t\t\t\t\thref=\"javascript:void(0)\">系统日志</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</dd>\r\n");
      out.write("\t\t</dl>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</aside>\r\n");
      out.write("\t<div class=\"dislpayArrow hidden-xs\">\r\n");
      out.write("\t\t<a class=\"pngfix\" href=\"javascript:void(0);\"\r\n");
      out.write("\t\t\tonClick=\"displaynavbar(this)\"></a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<section class=\"Hui-article-box\">\r\n");
      out.write("\t<div id=\"Hui-tabNav\" class=\"Hui-tabNav hidden-xs\">\r\n");
      out.write("\t\t<div class=\"Hui-tabNav-wp\">\r\n");
      out.write("\t\t\t<ul id=\"min_title_list\" class=\"acrossTab cl\">\r\n");
      out.write("\t\t\t\t<li class=\"active\"><span title=\"我的桌面\" data-href=\"welcome.html\">我的桌面</span>\r\n");
      out.write("\t\t\t\t\t<em></em></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"Hui-tabNav-more btn-group\">\r\n");
      out.write("\t\t\t<a id=\"js-tabNav-prev\" class=\"btn radius btn-default size-S\"\r\n");
      out.write("\t\t\t\thref=\"javascript:;\"><i class=\"Hui-iconfont\">&#xe6d4;</i></a><a\r\n");
      out.write("\t\t\t\tid=\"js-tabNav-next\" class=\"btn radius btn-default size-S\"\r\n");
      out.write("\t\t\t\thref=\"javascript:;\"><i class=\"Hui-iconfont\">&#xe6d7;</i></a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"iframe_box\" class=\"Hui-article\">\r\n");
      out.write("\t\t<div class=\"show_iframe\">\r\n");
      out.write("\t\t\t<div style=\"display: none\" class=\"loading\"></div>\r\n");
      out.write("\t\t\t<iframe scrolling=\"yes\" frameborder=\"0\" src=\"welcome.html\"></iframe>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"contextMenu\" id=\"Huiadminmenu\">\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li id=\"closethis\">关闭当前</li>\r\n");
      out.write("\t\t\t<li id=\"closeall\">关闭全部</li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--_footer 作为公共模版分离出去-->\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"lib/jquery/1.9.1/jquery.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"lib/layer/2.4/layer.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"static/h-ui/js/H-ui.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"static/h-ui.admin/js/H-ui.admin.js\"></script>\r\n");
      out.write("\t<!--/_footer 作为公共模版分离出去-->\r\n");
      out.write("\r\n");
      out.write("\t<!--请在下方写此页面业务相关的脚本-->\r\n");
      out.write("\t<script type=\"text/javascript\"\r\n");
      out.write("\t\tsrc=\"lib/jquery.contextmenu/jquery.contextmenu.r2.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("$(function(){\r\n");
      out.write("\t/*$(\"#min_title_list li\").contextMenu('Huiadminmenu', {\r\n");
      out.write("\t\tbindings: {\r\n");
      out.write("\t\t\t'closethis': function(t) {\r\n");
      out.write("\t\t\t\tconsole.log(t);\r\n");
      out.write("\t\t\t\tif(t.find(\"i\")){\r\n");
      out.write("\t\t\t\t\tt.find(\"i\").trigger(\"click\");\r\n");
      out.write("\t\t\t\t}\t\t\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\t'closeall': function(t) {\r\n");
      out.write("\t\t\t\talert('Trigger was '+t.id+'\\nAction was Email');\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});*/\r\n");
      out.write("});\r\n");
      out.write("/*个人信息*/\r\n");
      out.write("function myselfinfo(){\r\n");
      out.write("\tlayer.open({\r\n");
      out.write("\t\ttype: 1,\r\n");
      out.write("\t\tarea: ['300px','200px'],\r\n");
      out.write("\t\tfix: false, //不固定\r\n");
      out.write("\t\tmaxmin: true,\r\n");
      out.write("\t\tshade:0.4,\r\n");
      out.write("\t\ttitle: '查看信息',\r\n");
      out.write("\t\tcontent: '<div>管理员信息</div>'\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/*资讯-添加*/\r\n");
      out.write("function article_add(title,url){\r\n");
      out.write("\tvar index = layer.open({\r\n");
      out.write("\t\ttype: 2,\r\n");
      out.write("\t\ttitle: title,\r\n");
      out.write("\t\tcontent: url\r\n");
      out.write("\t});\r\n");
      out.write("\tlayer.full(index);\r\n");
      out.write("}\r\n");
      out.write("/*图片-添加*/\r\n");
      out.write("function picture_add(title,url){\r\n");
      out.write("\tvar index = layer.open({\r\n");
      out.write("\t\ttype: 2,\r\n");
      out.write("\t\ttitle: title,\r\n");
      out.write("\t\tcontent: url\r\n");
      out.write("\t});\r\n");
      out.write("\tlayer.full(index);\r\n");
      out.write("}\r\n");
      out.write("/*产品-添加*/\r\n");
      out.write("function product_add(title,url){\r\n");
      out.write("\tvar index = layer.open({\r\n");
      out.write("\t\ttype: 2,\r\n");
      out.write("\t\ttitle: title,\r\n");
      out.write("\t\tcontent: url\r\n");
      out.write("\t});\r\n");
      out.write("\tlayer.full(index);\r\n");
      out.write("}\r\n");
      out.write("/*用户-添加*/\r\n");
      out.write("function member_add(title,url,w,h){\r\n");
      out.write("\tlayer_show(title,url,w,h);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\t<!--此乃百度统计代码，请自行删除-->\r\n");
      out.write("\t<script>\r\n");
      out.write("var _hmt = _hmt || [];\r\n");
      out.write("(function() {\r\n");
      out.write("  var hm = document.createElement(\"script\");\r\n");
      out.write("  hm.src = \"https://hm.baidu.com/hm.js?080836300300be57b7f34f4b3e97d911\";\r\n");
      out.write("  var s = document.getElementsByTagName(\"script\")[0]; \r\n");
      out.write("  s.parentNode.insertBefore(hm, s);\r\n");
      out.write("})();\r\n");
      out.write("</script>\r\n");
      out.write("\t<!--/此乃百度统计代码，请自行删除-->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
